# Generated by Django 2.2.7 on 2020-02-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20200213_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='production_unit',
            field=models.IntegerField(choices=[(1, 'Caravans'), (2, 'Pop-Top / Campers')]),
        ),
        migrations.AlterField(
            model_name='monthplanning',
            name='production_unit',
            field=models.IntegerField(choices=[(1, 'Caravans'), (2, 'Pop-Top / Campers')]),
        ),
    ]
