# Generated by Django 2.2.7 on 2020-03-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_remove_ordertransport_watertest_date'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='watertest_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
