# Generated by Django 2.2.7 on 2020-09-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20200519_0618'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='actual_watertest_date',
        #     new_name='detailing_date',
        # ),
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='planned_watertest_date',
        #     new_name='watertest_date',
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
