# Generated by Django 2.2.7 on 2020-09-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20200911_1337'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='actual_watertest_date',
        #     new_name='collection_date',
        # ),
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='planned_watertest_date',
        #     new_name='detailing_date',
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='email_sent',
        #     field=models.DateField(blank=True, null=True),
        # ),
<<<<<<< HEAD
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
=======
        migrations.AddField(
            model_name='ordertransport',
            name='plumbing_comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordertransport',
            name='plumbing_date',
            field=models.DateField(blank=True, null=True),
        ),
>>>>>>> 575bd8a765bd5644985e00363a0b1881eb80e817
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='watertest_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
