# Generated by Django 2.2.7 on 2020-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20201019_2057'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='contractorscheduleexportcolumn',
        #     options={'ordering': ('sequence', 'name')},
        # ),
        # migrations.RemoveField(
        #     model_name='ordertransport',
        #     name='actual_watertest_date',
        # ),
        # migrations.RemoveField(
        #     model_name='ordertransport',
        #     name='planned_watertest_date',
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='email_sent',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='watertest_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='contractorscheduleexportcolumn',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
