# Generated by Django 2.2.7 on 2020-10-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0027_auto_20201019_2144'),
        ('schedule', '0024_auto_20201019_2117'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='contractorscheduleexportcolumn',
        #     options={'ordering': ('sequence', 'name')},
        # ),
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='actual_watertest_date',
        #     new_name='collection_date',
        # ),
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='planned_watertest_date',
        #     new_name='detailing_date',
        # ),
        # migrations.RemoveField(
        #     model_name='contractorscheduleexportcolumn',
        #     name='code',
        # ),
        migrations.AddField(
            model_name='contractorscheduleexportcolumn',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='caravans.SKU'),
        ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='email_sent',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='watertest_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
