# Generated by Django 2.2.7 on 2020-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_auto_20201109_2301'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='contractorscheduleexportcolumn',
        #     options={'ordering': ('sequence', 'name')},
        # ),
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='actual_watertest_date',
        #     new_name='purchase_order_raised_date',
        # ),
        # migrations.RenameField(
        #     model_name='ordertransport',
        #     old_name='planned_watertest_date',
        #     new_name='senior_designer_verfied_date',
        # ),
        # migrations.RemoveField(
        #     model_name='contractorscheduleexportcolumn',
        #     name='code',
        # ),
        # migrations.RemoveField(
        #     model_name='contractorscheduleexportcolumn',
        #     name='sku',
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='collection_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='detailing_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='email_sent',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='plumbing_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='watertest_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_comments',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='ordertransport',
        #     name='weigh_bridge_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
