# Generated by Django 2.2.7 on 2020-11-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderseries_production_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='type',
            field=models.IntegerField(choices=[(1, 'Customer Plan'), (2, 'Factory Plan'), (3, 'Chassis Plan'), (4, 'Contract'), (5, 'Handover to driver form'), (6, 'Handover to dealership form'), (7, 'Order Certificate')]),
        ),
    ]
