# Generated by Django 2.2.7 on 2020-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201113_1101'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='orderdocument',
        #     name='cert_title',
        #     field=models.CharField(blank=True, max_length=500),
        # ),
    ]
