# Generated by Django 2.2.7 on 2020-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201118_1710'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='orderdocument',
        #     name='cert_status',
        #     field=models.CharField(blank=True, max_length=500),
        # ),
    ]
