# Generated by Django 2.2.7 on 2020-11-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_delete_certdocs_deleted'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CertificateDeleted',
        #     fields=[
        #         ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('cert_title', models.CharField(blank=True, max_length=500)),
        #         ('cert_status', models.CharField(blank=True, max_length=500)),
        #         ('doc_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.OrderDocument')),
        #         ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
        #     ],
        #     options={
        #         'verbose_name': 'Certificates Deleted',
        #         'verbose_name_plural': 'Certificates Deleted Details',
        #         'db_table': 'certificates_deleted',
        #         'ordering': ('order',),
        #     },
        # ),
    ]
