# Generated by Django 2.2.7 on 2020-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_certificatedeleted'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='certificatedeleted',
        #     name='doc_id',
        #     field=models.CharField(blank=True, max_length=500),
        # ),
    ]
