# Generated by Django 2.2.7 on 2020-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200205_1507'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='build',
        #     name='vin_number',
        #     field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='VIN Appointed'),
        # ),
    ]
