# Generated by Django 2.2.7 on 2020-11-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20201109_2311'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='build',
        #     name='vin_number',
        #     field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='VIN Appointed'),
        # ),
    ]
