# Generated by Django 2.2.7 on 2020-11-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20201110_1920'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='build',
        #     name='vin_number',
        #     field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='VIN Appointed'),
        # ),
    ]
