# Generated by Django 2.2.7 on 2020-03-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0012_auto_20200225_1830'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='series',
        #     name='avg_ball_weight_max',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='avg_ball_weight_min',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='avg_tare_weight_max',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='avg_tare_weight_min',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='height_max_incl_ac_feet',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='height_max_incl_ac_inches',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='length_feet',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='length_inches',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='length_incl_aframe_feet',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='length_incl_aframe_inches',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='length_incl_bumper_feet',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='length_incl_bumper_inches',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='width_feet',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='width_inches',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='width_incl_awning_feet',
        # ),
        # migrations.RemoveField(
        #     model_name='series',
        #     name='width_incl_awning_inches',
        # ),
    ]
