# Generated by Django 2.2.7 on 2020-03-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0013_auto_20200312_1534'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='series',
        #     name='avg_ball_weight',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='avg_tare_weight',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='height_max_incl_ac_mm',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='length_incl_aframe_mm',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='length_incl_bumper_mm',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='length_mm',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='width_incl_awning_mm',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='width_mm',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
