# Generated by Django 2.2.7 on 2020-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0014_auto_20200312_1535'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_incl_aframe_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Length (incl A-Frame) in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Length in mm'),
        # ),
    ]
