# Generated by Django 2.2.7 on 2020-03-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0015_auto_20200312_1911'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='series',
        #     name='avg_ball_weight',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Avg Ball Weight in kg'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='avg_tare_weight',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Avg Tare Weight in kg'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='height_max_incl_ac_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max Height (incl A/C) in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_incl_bumper_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Length (incl Bumper) in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='width_incl_awning_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Width (incl Awning) in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='width_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Width in mm'),
        # ),
    ]
