# Generated by Django 2.2.7 on 2020-03-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0016_auto_20200312_1917'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='series',
        #     name='height_max_incl_ac_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max Height Internal in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_incl_aframe_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Travel Length in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_incl_bumper_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max Height External in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='width_incl_awning_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max Width (incl Awning) in mm'),
        # ),
    ]
