# Generated by Django 2.2.7 on 2020-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0018_auto_20200318_1729'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_incl_aframe_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Travel Length in mm'),
        # ),
    ]
