# Generated by Django 2.2.7 on 2020-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0019_auto_20200318_1800'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='series',
        #     name='height_max_incl_ac_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max Internal Living Height in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_incl_bumper_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max Extrernal Travel Height in mm'),
        # ),
        # migrations.AlterField(
        #     model_name='series',
        #     name='width_incl_awning_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max_Travel Width in mm'),
        # ),
    ]
