# Generated by Django 2.2.7 on 2020-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0020_auto_20200327_1654'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='series',
        #     name='width_incl_awning_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max Travel Width in mm'),
        # ),
    ]
