# Generated by Django 2.2.7 on 2020-03-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0021_auto_20200327_1655'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='series',
        #     name='length_incl_bumper_mm',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='Max External Travel Height in mm'),
        # ),
    ]
