# Generated by Django 2.2.7 on 2020-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravans', '0023_auto_20200831_2053'),
    ]

    operations = [
<<<<<<< HEAD
        # migrations.AddField(
        #     model_name='series',
        #     name='series_type',
        #     field=models.CharField(choices=[('Caravans', 'Caravans'), ('PopTops', 'PopTops'), ('Campers', 'Campers')], default='Caravans', max_length=32),
        # ),
=======
        migrations.AddField(
            model_name='series',
            name='series_type',
            field=models.CharField(choices=[('Caravans', 'Caravans'), ('PopTops', 'PopTops'), ('Campers', 'Campers')], default='Caravans', max_length=32),
        ),
>>>>>>> 575bd8a765bd5644985e00363a0b1881eb80e817
    ]
