# Generated by Django 2.2.7 on 2020-03-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20200302_1558'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ordertransport',
        #     name='watertest_date',
        # ),
    ]
