# Generated by Django 2.2.7 on 2020-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_ordertransport_watertest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransport',
            name='collection_comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordertransport',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertransport',
            name='email_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
